#!/bin/sh
#
# Starts deingena script.
#


start() {
	chmod -R 777 /workspace/init_script.sh
	sh /workspace/init_script.sh
}
stop() {
	chmod -R 777 /workspace/init_script.sh
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
